### ISSUE TITLE
Pulse AND Silence Lengths?

### ISSUE THREAD

**Issue by ahnyerkeester** [latchdevel/raspicode#2]
First, this is great, thank you for your work on it!

Is it possible to set different pulse **and** silence times? For example, I assume:

`c:010;p:377,765@`

will send a pulse 377ms long, silence for ??, send a pulse 765ms long, silence for ??, send a pulse 377ms long.

For my project (using the same example), I need to send a pulse 377ms long, silence for 765ms, send a pulse 765ms long, silence for 377ms, send a pulse 377ms long, silence for 765ms.

I hope this make sense and it may already be possible and I just haven't figured it out.

**Comment by latchdevel** [comment]
Hello,

I'm glad you liked it, but, by the way, I haven't seen your star...

Of course, this is just what it does.

The "pilight string C:" is an OOK (On-Off Key) code. Odd positions represent "On" (high pulse state) and
even the positions represent "Off" (low pulse state) or silences as you say.

For this reason, the number of characters in C: should always be even, so that the transmission ends low and does not leave the transmitter on.

In a single transmission the duration of the last pulse is irrelevant, but normally transmissions are repeated several times, so the last pulse is called a footer pulse, and really work to establish the pause or silence between transmissions.

However, the duration of the pulses indicated is very, very high, it surely does not correspond to an ASK/OOK radio frequency transmission.

The "Pilight string P:" is a list of pulse-type durations in microseconds, not milliseconds.

By default, the maximum pulse size is set to 100000 us (100ms), so you will have to [modify this value in the source code](https://github.com/latchdevel/raspicode/blob/ba3f29bd1e0ce95cb96fc923b6555b43205448f1/wiringpiook/wiringpiook.c#L16) before compiling.

And you may also need to increase the total transmission time, which [by default is set to 2000 ms](https://github.com/latchdevel/raspicode/blob/ba3f29bd1e0ce95cb96fc923b6555b43205448f1/wiringpiook/wiringpiook.c#L18C9-L18C20).

If you increase these values, your example: 

`send a 377 ms long pulse, 765 ms silence, send a 765 ms long pulse, 377 ms silence, send a 377 ms long pulse, 765 ms silence.`

It's like this picode:  `c:011001;p:377000,765000@`

I hope I have been able to help you, see your star, and that you tell me if it has worked for you.
Best regards.

**Comment by ahnyerkeester** [comment]
Star coming up! And you're right, I didn't mean "ms" I meant "𝜇s". I'd just watched a series of videos on how to analyze the pulse train and the first pulse he was dealing with was 12ms so I got it stuck in my head.

So the first pulse will be high and of whatever duration I assign it and the second pulse will be low for whatever pulse I assign. That's good news. I think I understand how to construct my pulse train now.

**Comment by ahnyerkeester** [comment]
It worked. It nearly broke my brain figuring it out, but it worked! I was confused on how to get the binary code needed to control my blinds translated into a pulse train to ACTUALLY control my blinds. I bought a Flipper Zero so I could record the codes. It took me a while of digging through the code in the Flipper to understand what I was looking at. And your very clear, very helpful answer here helped me translate a binary string into a Pilight string that would send the pulses to control my blinds.

So now that I have raised one of my blinds using a Raspberry Pi, I can build out the rest of the project. I'm using HAP-NodeJS to add an Accessory to HomeKit so I can have Siri raise and lower the blinds that don't have that capability natively. A few years ago I built a controller for my evaporative cooler to do the same thing. I cannot thank you enough. This code is EXACTLY what I needed and will make the project a lot more elegant than I'd feared.

**Comment by latchdevel** [comment]
Great! I'm very glad it worked for you.

Once you get the pulse train, it is easy to represent it in "picode" format, since there are several tools for this.

For example "**picoder**": https://github.com/latchdevel/picoder
Which is even available as executable binary for macOS, Linux and Windows.

```
$ picoder convert -t "377,765,765,377,377,765"
c:011001;p:377,765@

$ picoder convert -s "c:011001;p:377,765@"
pulses[6]={377,765,765,377,377,765};
```

And I also recently published a python module "https://github.com/latchdevel/pyPiCode" that implements the functions of the original library, which includes the function `pulseTrainToString(pulses_list: list, repeats: int = 0)` that converts a list of pulses to a string in pilight format:

```python

>>> import pypicode as picode
>>>
>>> picode.pulseTrainToString([377,765,765,377,377,765])
'c:011001;p:377,765@'
>>>
>>> picode.stringToPulseTrain("c:011001;p:377,765@")
[377, 765, 765, 377, 377, 765]
>>>
```

Keep telling me how the project is going.
Ask anything you need.
Greetings.

**Comment by ahnyerkeester** [comment]
Those utilities look great but I'm doing the encoding in javascript inside the accessory definition for HAP-NodeJS. That way, I can have raspicode running and curl the command to localhost.local all on the same RPi.

I had it working for a bit last night but when I used the manual slider in the Home app, the shade would just move up and down and stop. When I told Siri to close the blind, it stopped working. I have some more troubleshooting to do but I'm well past the hard part now. raspicode was exactly what I needed to make this work.

**Comment by ahnyerkeester** [comment]
Just to wrap this all up, I'm done. It works. I have two motorized Coolaroo outdoor blinds on my sunroom. They're controlled by Dooya DC3100 remotes but now I can control with Siri via a Raspberry Pi running raspicode and HAP-NodeJS.

There is one part of the project I'm not happy about, but that's because of Apple HomeKit, NOT raspicode. To lower the blinds to a preprogrammed stop instead of all the way down, you have to send the STOP code 5 times with a slight pause between each one. I could do it with raspicode via the web interface, but I couldn't get the HomeKit accessory to handle the pause between commands correctly.

The part I'm not happy about is that to get it to work, the HomeKit accessory runs a Python script I wrote and passes it some codes. That Python script formats the Pilight string and curls it to raspicode. If the code is DOWN, the script repeats it 5x with the delay. It is klugey but it works.

Thank you again Jorge! Your patient explanation of how raspicode works brought it all together for me.

**Comment by latchdevel** [comment]
The same thing happened to a friend with the STOP code on his blinds.

We were able to fix this by adding the pause between transmissions as a "picode" footer pulse.
"Raspicode" supports sending multi-line picodes, you can join several picodes by adding the pause you need in one of them.

So, my friend's command to stop the blind was composed of these two "picodes" together, which you must resend several times:
```
c:3012212112211212211221211212211212212121212112212121212121121212211221122112211224;p:1460,360,720,4800,4200;r:4@
c:3012212112211212211221211212211212212121212112212121212121121212211221122112211224;p:1460,360,720,4800,18140;r:1@
```

It has been a pleasure to have helped you.
Best regards.

**Comment by ahnyerkeester** [comment]
I'd forgotten that picodes can do multi-line codes. I'll have to experiment with it. I'm much rather not have that gateway Python script if I can avoide it. I'll give this a shot.

**Comment by ahnyerkeester** [comment]
I tried the `r:` parameter and multiple lines in the web interface in a bunch of different combinations. Even expanded the time for the final pulse. Nothing worked.

I'm thinking about trying to slightly modify raspicode to add a `z:` parameter which can only be used with `r:` to insert a delay between each repeat. I would much rather be able to send the codes straight from the accessory than having my gateway in the middle.

I think I can do it because you've written the code so clearly. Since I spent time digging through the code to understand what it was doing, it inspired me to write my gateway code better.

**Comment by latchdevel** [comment]
Hi,

I don't know where the problem you are having is, but I'm sure that the code you need can be represented by "picodes".

The "Dooya" or blinds protocol in general, is relatively common, it has already been discussed in other projects:
 - https://github.com/rjcarlson49/Xmit_433.0
 - https://forum.mysensors.org/topic/7/controlling-blinds-com-rf-dooya-motors-with-arduino-and-vera

Its decoding and even encoding are supported by different systems, for example RFLink, which generates these three picodes as a STOP command: `10;BrelMotor;6964fb;f1;STOP;`
```
c:01233232233223233223323223233223233232323232233232323232322323233223322332322332230;p:4730,1470,360,730;r:1@
c:1233232233223233223323223233223233232323232233232323232322323233223322332322332230;p:4730,1470,360,730;r:9@
c:123323223322323322332322323322323323232323223323232323232232323322332233232233220;p:4730,1470,360,730;r:1@
```

Perhaps the capture you are using is not entirely accurate or its format is not easy to convert.
If you can share the raw capture, maybe it's possible to find the solution.

Regards.

**Comment by ahnyerkeester** [comment]
You know Jorge, you're right. I need to slow down here a bit.

I'm sure the codes are correct. I used a Flipper Zero to capture them and they have some great videos on how to analyze captures. Also, I can raise, lower all the way, and stop the shades without the kluge. The only ways I can get them to go to the pre-programmed stop point is with the stop code in the raspicode web interface and clicking the transmit button repeatedly till it sends 5 times or with this bit of code:
```
sendpulsetrain(pulsetrain_intro+processedstring+pulsetrain_end)

if (rawkey == rawstop):
  i = 1
  while i < 5:
    # This delay very closely mimics what the remote control does.
    sleep(0.25)
    sendpulsetrain(pulsetrain_intro+processedstring+pulsetrain_end)
    i +=1
```
When I get a chance, I think I'll try playing with the `r:` parameter some more. It _seems_ like that should be able to work. I'll have Flipper Zero capture the result and analyze how it is different.

Thanks again for your patience!

**Comment by ahnyerkeester** [comment]
I captured the long stop signal from the remote, removed the noise and extracted one pulse train to [a csv](https://github.com/user-attachments/files/16041796/remote2.csv). I verified my code is correct. But I noticed that there seems to be a very long high and low before the code is sent so I modified the string I send through the web interface:

`c:562301010110100101011010100110011010101010100110100101010101011001100110011001100114;p:366,733,4758,1466,7756,6500,1500;r:5@`

The log shows:

`[2024-06-29 11:07:21,142] 1014 INFO - 192.168.68.132 POST http://shady.local:8087/ 200 OK RF TX sent picode in 329 ms OK`

I don't think it could send that pulse train five times in only 329 ms so I did a RAW capture with my Flipper Zero. Here's the remote:
<img width="862" alt="remote" src="https://github.com/latchdevel/raspicode/assets/45885366/411b4204-1c8a-4c98-b4ba-55cee4db6995">
and here's the web interface:
<img width="862" alt="webinterface" src="https://github.com/latchdevel/raspicode/assets/45885366/13d7dd7d-efc0-41f3-9cc1-39a71c61c044">

Am I formatting the string incorrectly for the web interface? Doesn't the `;r:5` mean  "repeat that string 5 times"?

**Comment by ahnyerkeester** [comment]
Deleted my last post because I did more testing and that one is obsolete now.

Using my Flipper Zero, I recorded the remote delivering the "down to programmed stop" command. Here is the raw data: [Remote1.txt](https://github.com/user-attachments/files/16059370/Remote1.txt)

Then I tried to duplicate what I was seeing there through the web interface using these commands:
```
c:3401010110100101011010100110011010101010100110100101010101011001100101011001010112;p:366,733,7750,6500,1500;r:2@
c:3401010110100101011010100110011010101010100110100101010101011001100101011001010112;p:366,733,7750,4500,1500;r:10@
```
Again, this didn't work. When I recorded the pulse train generated by the website and put it side by side with one I recorded from the remote, they look identical to me.

So far, the only way I can get it to work is with my gateway kluge.

**Comment by latchdevel** [comment]
Hi.

It looks like you may be right. The **Brel Motor / Dooya protocol (DC318/DC114)** is a bit strange.
This protocol is described in RFLink Plugin_083: https://github.com/couin3/RFLink/blob/master/RFLink/Plugins/Plugin_083.c

It is possible to encode and decode. But I don't understand it very well, since in practice each command sents two frames of 82 pulses repeated 11 times, with a little pause between each frame.

The picodes that you mention in the last post are the "UP" command:
`BrelMotor;ID=18ebf6;SWITCH=05;CMD=UP;`
```
c:3401010110100101011010100110011010101010100110100101010101011001100101011001010112;p:366,733,7750,4500,1500;r:10@
```

However, the picodes of the post you deleted are the "STOP" command:
`BrelMotor;ID=18ebf6;SWITCH=05;CMD=STOP;`
```
c:2301010110100101011010100110011010101010100110100101010101011001100110011001100114;p:366,733,4758,1466,7756;r:10@
```

I have not yet been able to analyze the RAW capture, although without having the transmitter and receiver I think it will be a complicated task. At the moment I can only emulate both by RFLink implementing.

Try this multiline picode to STOP:
```
c:1232323323223232332323223322332323232323223323223232323232332233223322332233223320;p:4735,1475,355,735;r:11@
c:1232323323223232332323223322332323232323223323223232323232332233223322332322332230;p:4735,1475,355,735;r:11@
```

Good luck!

**Comment by ahnyerkeester** [comment]
Yes, to get the blinds to go to the programmed down position rather than all the way down, you have to send the STOP command multiple times.

The commands you suggested didn't work either. I have a good capture of the remote so next I grab a capture of these commands that we've tried and see what we're missing. This is a tough puzzle but I'm sure we can get it!

Thanks again. I'll let you know what I find.

**Comment by ahnyerkeester** [comment]
I got it. Finally. 
**BOTTOM LINE:** Dooya's "lower to programmed spot" requires the STOP command be sent for 2 seconds or more. I had to change the max time and max repeats in picode.py and piwiringook.c to make it work. I repeat the code 35x which puts it over 2 sec.
**HOW I GOT THERE:**
I did a side-by-side comparison of the captured pulse trains for the remote (works), the gateway program I wrote (works) and the web interface with `r:20` (doesn't work).  The pulse trains all look identical. The only thing that was different was how long they transmitted.

I just closed the blinds to the programmed spot by having the HAP-NodeJS accessory curl the command with  `r:35`.  Only problem is that though I can close the blinds individually, when I say "close all the blinds in the sunroom" the logs all show the commands as having been sent, but nothing happens. Still need to do some work.

What would have made this easier was if Dooya published their standards.

Once more Jorge, thank you. You've been a gentleman and a tremendous help.

**Comment by latchdevel** [comment]
I'm glad you're on the right track.

Once again, just the same thing that happened to my friend.
To leave the blind in a specific position, you needed to send a command for a specific period of time, as if you were pressing the button on the remote control.

For this reason, I added an additional parameter to the standard Pilight, the **`t:`** key, for a "**timed**" picode transmission.
It is incompatible and takes precedence over `r:` Its value will be the **seconds** during which the picode will be transmitted repeatedly. You should be careful, because no duration limit check is performed.

This picode will be transmitted repeatedly for 2 seconds:
`c:12323233232232323323232233223323232323223232332233223322332233223320;p:4735,1475,355,735;t:2@`

You can take a look at the code to see how it works:
https://github.com/latchdevel/raspicode/blob/ba3f29bd1e0ce95cb96fc923b6555b43205448f1/raspicode.py#L232

I didn't think anyone would need this, and I didn't document it properly. It's my fault.

I hope it helps.
Regards.

**Comment by ahnyerkeester** [comment]
Just tested it and it works!

Finally, a more elegant solution than modifying your code or using my kluge. The HAP-NodeJS accessory builds the Pilight string based on the command then curl's it directly to raspicode. Jorge, you wrote some solid code. Covered all the bases. Thank you so very much!

I think the only solution to being able to close both blinds with a single Siri command will be to set up a second Raspberry Pi with each one running a single shade. I'll have to think about it.
